
pollution <- read.csv("avgpm25.csv")
head(pollution)
tail(pollution)
str(pollution)
summary(pollution)
boxplot(pollution$pm25,col="blue")
hist(pollution$pm25,col="green")
rug(pollution$pm25)
abline(v = 12)
abline(v = median(pollution$pm25),lwd=5,color="red")
rug(pollution$pm25)
table(pollution$region)
barplot(table(pollution$region))
boxplot(pm25 ~ region, data = pollution, col = "red",ylab="pollution", main="cool boxplot")
par(mfrow=c(2,1),mar=c(4,4,2,2))
hist(subset(pollution,region == "east")$pm25,col="green")
abline(v = median(subset(pollution,region == "east")$pm25),lwd=4)
hist(subset(pollution,region == "west")$pm25,col="blue")
abline(v = median(subset(pollution,region == "west")$pm25),lwd=4)
par(mfrow=c(1,1))
plot(pollution$pm25,pollution$latitude)
plot(pollution$pm25,pollution$latitude,col=pollution$region)
legend(5,40,legend=unique(pollution$region),pch=1)
